language: php

sudo: false

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - COMPOSER_FLAGS='--no-interaction --no-progress --no-suggest --prefer-dist'

matrix:
  include:
    - php: '7.1'
      env: DEPLOY=true
    - php: '7.2'
    - php: '7.2'
      env: PHAR_READONLY='true'
    - php: '7.2'
      env: COVERAGE='true'
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - |
    if [ "$COVERAGE" != "true" ]; then
        phpenv config-rm xdebug.ini || true
    fi
  - set -eo pipefail
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer validate
  - |
    if [ "DEPLOY" != "true" ]; then
        composer config --unset platform.php
        composer update --lock
    fi

install:
  - composer install $COMPOSER_FLAGS

script:
  - bin/box validate
  - |
    if [ "$COVERAGE" == "true" ]; then
        make tm
    elif [ "PHAR_READONLY" == "true" ]; then
        make tu_box_phar_readonly
    else
        make test
    fi

notifications:
    email: false

deploy:
  provider: releases
  api_key:
    secure: Cw4LQm+uiQ7BuCVKAzaoxsj2OnpMv3dB0Fu5DBnYNJ4t5D2TFLZqVWnyyv2wx0kSO5uHEy8JwIavEk5kqWBZTuNSYNmE+EsucVOkLfMybsnQ+1e8CXsOPHlGwmVA5HSUIdx/vBEuUkdA6QgOOlFn/qfI4oRHa/CwiFsy9KPCnQ+RfLYYsH0l9SGEtVKqLMEly7qXdr/3OXn5fGKDAzntfuSYdq84jkVcWq8vBM9j5CQ9ZBm0Tfs5zrjedJ16Fdb3YXyb1FZahcdQQN7jLhLT6UYZVdaHHqgLN/vPIfV9PPGSBpIYzVWbGF1NTGPS6A8JjxsG3ylAnGj0VnrPf9WFC+1JuBasmeVhmWt+UDwZVRd83IxAoHKr0qsKDZ6/uCFljLWeOhQhcJ78O8LxqGQVl9JwMgWFmp5WtNFihde3IIFmNr2UL9R3rmchbvLoxupp6xBFklvFa23FRMe1wdxhb1b/Qmyf0ETaKFSwfYEnsgQVxI1sDOXXJRJuFtPIjBX9AFhW6NLBoE8EKYpHPdSQ1P/sH71Wt6lxW5WLWF94cKYQnVWuDIVf+beHLeP4tWy9Sd1Bdg2dYXlaR3wzyUwIb5A82EQ4IwmUeJUWFd1p+Sd5jlSnppB6hFO+FTlhHV77CI0o/lqcgAwKU4o1RZ6MT+38/iK9KMAUlQ69ywPhZ0A=
  file: bin/box.phar
  skip_cleanup: true
  on:
    tags: true
    repo: humbug/box
    condition: "$DEPLOY"
