language: php

sudo: false

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - COMPOSER_FLAGS='--no-interaction --no-progress --no-suggest --prefer-dist'

matrix:
  include:
    - php: '7.2'
    - php: '7.2'
      env: COVERAGE='true'
    - php: '7.2'
      env: SYMFONY_VERSION='v3'
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - |
    if [ "$COVERAGE" != "true" ]; then
        phpenv config-rm xdebug.ini || true
    fi
  - set -eo pipefail
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer validate
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        composer require --no-update "symfony/lts:${SYMFONY_VERSION}"
    fi

install:
  - |
    if [ -n "$SYMFONY_VERSION" ]; then
        composer update $COMPOSER_FLAGS
    else
        composer install $COMPOSER_FLAGS
    fi

script:
  - |
    if [ "$COVERAGE" == "true" ]; then
        make tm
    else
        make test
    fi

notifications:
    email: false
